export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_AUTH_REFRESH = 'USER_AUTH_REFRESH';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_CREATE_FAIL = 'USER_CREATE_FAIL';
